vim.cmd("set expandtab")
vim.cmd("set tabstop=2")
vim.cmd("set softtabstop=2")
vim.cmd("set shiftwidth=2")
vim.cmd("set ignorecase")
vim.cmd("set smartcase")
vim.cmd("set mouse=a")
vim.cmd("set number")
vim.cmd("set relativenumber")
vim.cmd("set guicursor=n-v-c:block,i-ci-ve:ver25,r-cr:hor20,o:hor50,a:blinkwait5-blinkoff5-blinkon5-Cursor/lCursor,sm:block-blinkwait5-blinkoff5-blinkon5")
vim.cmd("set clipboard+=unnamedplus")
vim.cmd("let mapleader = \"-\"")
